sudo: required
services:
  - docker
before_install:
  - docker build -t waterstones/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true waterstones/react-test npm test
after_success:
  - docker build -t waterstones/multi-client ./client
  - docker build -t waterstones/multi-nginx ./nginx
  - docker build -t waterstones/multi-server ./server
  - docker build -t waterstones/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push waterstones/multi-client
  - docker push waterstones/multi-nginx
  - docker push waterstones/multi-server
  - docker push waterstones/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-031289315968
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
